/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LocalAgentChatPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/adapters/codexAdapter.ts
var PROMPT_PLACEHOLDER = "{prompt}";
var VAULT_PLACEHOLDER = "{vaultPath}";
var CWD_PLACEHOLDER = "{cwd}";
var SESSION_PLACEHOLDER = "{sessionId}";
var CodexCLIAdapter = class {
  constructor(getSettings) {
    this.getSettings = getSettings;
  }
  buildCommand(input, context) {
    const settings = this.getSettings();
    const cwd = settings.defaultCwd.trim() || context.cwd;
    if (input.commandOverride?.trim()) {
      if (!settings.allowAnyCommand) {
        throw new Error("Command override is disabled by settings.");
      }
      const tokens = splitArgs(input.commandOverride.trim());
      if (tokens.length === 0) {
        throw new Error("Command override is empty.");
      }
      const [command, ...args] = tokens;
      return {
        command,
        args,
        cwd,
        displayCommand: quoteCommand(command, args)
      };
    }
    const template = settings.codexArgsTemplate.trim();
    const rawArgs = template.length > 0 ? splitArgs(template) : [];
    const hasPromptPlaceholder = rawArgs.some((arg) => arg.includes(PROMPT_PLACEHOLDER));
    const renderedArgs = rawArgs.map(
      (arg) => arg.replaceAll(PROMPT_PLACEHOLDER, input.prompt).replaceAll(VAULT_PLACEHOLDER, context.vaultPath).replaceAll(CWD_PLACEHOLDER, cwd).replaceAll(SESSION_PLACEHOLDER, context.sessionId)
    );
    if (!hasPromptPlaceholder) {
      renderedArgs.push(input.prompt);
    }
    return {
      command: settings.codexExecutablePath,
      args: renderedArgs,
      cwd,
      displayCommand: quoteCommand(settings.codexExecutablePath, renderedArgs)
    };
  }
  parseChunk(raw) {
    const lines = raw.split(/\r?\n/g).map((line) => line.trim()).filter((line) => line.length > 0);
    for (const line of lines) {
      if (!line.startsWith("{") || !line.endsWith("}")) {
        continue;
      }
      try {
        const parsed = JSON.parse(line);
        const text = pickText(parsed);
        if (text) {
          return { kind: "delta", text, raw: parsed };
        }
      } catch {
      }
    }
    return { kind: "delta", text: raw };
  }
  normalizeError(err) {
    if (err instanceof Error) {
      return {
        message: err.message,
        raw: err
      };
    }
    return {
      message: String(err),
      raw: err
    };
  }
};
function pickText(payload) {
  const knownKeys = ["text", "delta", "content", "message"];
  for (const key of knownKeys) {
    const value = payload[key];
    if (typeof value === "string" && value.length > 0) {
      return value;
    }
  }
  const nested = payload.data;
  if (nested && typeof nested === "object" && !Array.isArray(nested)) {
    for (const key of knownKeys) {
      const value = nested[key];
      if (typeof value === "string" && value.length > 0) {
        return value;
      }
    }
  }
  return null;
}
function quoteArg(arg) {
  if (/^[a-zA-Z0-9._:/\\-]+$/.test(arg)) {
    return arg;
  }
  return JSON.stringify(arg);
}
function quoteCommand(command, args) {
  return [quoteArg(command), ...args.map(quoteArg)].join(" ");
}
function splitArgs(raw) {
  const args = [];
  let current = "";
  let quote = null;
  let escaped = false;
  const pushCurrent = () => {
    if (current.length > 0) {
      args.push(current);
      current = "";
    }
  };
  for (const char of raw) {
    if (escaped) {
      current += char;
      escaped = false;
      continue;
    }
    if (char === "\\") {
      escaped = true;
      continue;
    }
    if (quote) {
      if (char === quote) {
        quote = null;
      } else {
        current += char;
      }
      continue;
    }
    if (char === '"' || char === "'") {
      quote = char;
      continue;
    }
    if (/\s/.test(char)) {
      pushCurrent();
      continue;
    }
    current += char;
  }
  if (escaped) {
    current += "\\";
  }
  pushCurrent();
  return args;
}

// src/safety/safetyPolicy.ts
var import_node_path = __toESM(require("node:path"));
var RISK_RULES = [
  {
    id: "rm-rf",
    reason: "Detected recursive delete command (`rm -rf`).",
    regex: /\brm\s+-rf\b/i
  },
  {
    id: "windows-del-recursive",
    reason: "Detected Windows recursive delete command (`del /s` or `rmdir /s`).",
    regex: /\b(del\s+\/[^\n\r]*\bs\b|rmdir\s+\/s\b)/i
  },
  {
    id: "sudo-or-priv-escalation",
    reason: "Detected privilege escalation command (`sudo`/`doas`/`runas`).",
    regex: /\b(sudo|doas|runas)\b/i
  },
  {
    id: "git-destructive",
    reason: "Detected destructive git command (`git reset --hard` or `git clean -fdx`).",
    regex: /\bgit\s+(reset\s+--hard|clean\s+-f(d|x)+)\b/i
  },
  {
    id: "filesystem-destructive-tools",
    reason: "Detected low-level disk/filesystem command (`mkfs`/`format`/`dd if=`).",
    regex: /\b(mkfs|format\s+[a-z]:|dd\s+if=)\b/i
  },
  {
    id: "shell-chaining",
    reason: "Detected shell chaining/piping that can hide compound operations (`&&`, `||`, `;`, `|`).",
    regex: /(&&|\|\||;|\|)/i
  },
  {
    id: "output-redirection",
    reason: "Detected output redirection (`>`/`>>`) which may overwrite files.",
    regex: /(^|\s)(>{1,2})(\s|$)/i
  }
];
var SafetyPolicy = class {
  assess(command, vaultPath) {
    const reasons = [];
    const matchedRules = [];
    const joinedCommand = [command.command, ...command.args].join(" ");
    for (const rule of RISK_RULES) {
      if (rule.regex.test(joinedCommand)) {
        matchedRules.push(rule.id);
        reasons.push(rule.reason);
      }
    }
    const resolvedVault = import_node_path.default.resolve(vaultPath);
    const resolvedCwd = import_node_path.default.resolve(command.cwd);
    if (!isInsidePath(resolvedVault, resolvedCwd)) {
      matchedRules.push("cwd-outside-vault");
      reasons.push(`Working directory is outside the vault: ${resolvedCwd}`);
    }
    const outsidePaths = extractAbsolutePaths(command.args).filter(
      (absolutePath) => !isInsidePath(resolvedVault, absolutePath)
    );
    if (outsidePaths.length > 0) {
      matchedRules.push("path-outside-vault");
      reasons.push(`Command references path(s) outside vault: ${outsidePaths.join(", ")}`);
    }
    return {
      isDangerous: reasons.length > 0,
      reasons,
      matchedRules
    };
  }
};
function extractAbsolutePaths(args) {
  const paths = [];
  for (const arg of args) {
    const token = arg.trim().replace(/^['"]|['"]$/g, "");
    if (!token) {
      continue;
    }
    if (/^https?:\/\//i.test(token)) {
      continue;
    }
    if (import_node_path.default.isAbsolute(token)) {
      paths.push(import_node_path.default.resolve(token));
    }
  }
  return paths;
}
function isInsidePath(basePath, targetPath) {
  const normalizedBase = import_node_path.default.resolve(basePath);
  const normalizedTarget = import_node_path.default.resolve(targetPath);
  if (process.platform === "win32") {
    const baseLower = normalizedBase.toLowerCase();
    const targetLower = normalizedTarget.toLowerCase();
    return targetLower === baseLower || targetLower.startsWith(`${baseLower}${import_node_path.default.sep}`);
  }
  return normalizedTarget === normalizedBase || normalizedTarget.startsWith(`${normalizedBase}${import_node_path.default.sep}`);
}

// src/settings.ts
var import_obsidian = require("obsidian");
var LocalAgentSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Local Agent Chat Settings" });
    new import_obsidian.Setting(containerEl).setName("Codex executable path").setDesc("Binary to execute (example: codex or full absolute path).").addText(
      (text) => text.setPlaceholder("codex").setValue(this.plugin.settings.codexExecutablePath).onChange(async (value) => {
        this.plugin.settings.codexExecutablePath = value.trim() || "codex";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Codex args template").setDesc("CLI args template. Placeholders: {prompt}, {vaultPath}, {cwd}, {sessionId}.").addTextArea(
      (text) => text.setPlaceholder('exec "{prompt}"').setValue(this.plugin.settings.codexArgsTemplate).onChange(async (value) => {
        this.plugin.settings.codexArgsTemplate = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default working directory").setDesc("Fallback CWD for command execution. Leave empty to use vault path.").addText(
      (text) => text.setValue(this.plugin.settings.defaultCwd).onChange(async (value) => {
        this.plugin.settings.defaultCwd = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Chat folder").setDesc("Vault folder path where session markdown files are stored.").addText(
      (text) => text.setValue(this.plugin.settings.chatFolder).onChange(async (value) => {
        this.plugin.settings.chatFolder = value.trim() || "AI Chats";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Allow any command").setDesc("If enabled, messages starting with `!cmd` can run arbitrary commands.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.allowAnyCommand).onChange(async (value) => {
        this.plugin.settings.allowAnyCommand = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Require danger confirmation").setDesc("Show a blocking confirmation modal for risky commands.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.dangerousConfirmEnabled).onChange(async (value) => {
        this.plugin.settings.dangerousConfirmEnabled = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Execution timeout (ms)").setDesc("Maximum runtime for each CLI invocation before forced cancellation.").addText(
      (text) => text.setValue(String(this.plugin.settings.executionTimeoutMs)).onChange(async (value) => {
        const parsed = Number(value);
        if (!Number.isNaN(parsed) && parsed > 0) {
          this.plugin.settings.executionTimeoutMs = parsed;
          await this.plugin.saveSettings();
        }
      })
    );
  }
};

// src/storage/sessionStore.ts
var import_obsidian2 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  codexExecutablePath: "codex",
  codexArgsTemplate: 'exec "{prompt}"',
  defaultCwd: "",
  chatFolder: "AI Chats",
  allowAnyCommand: true,
  dangerousConfirmEnabled: true,
  executionTimeoutMs: 3e5
};
function createId(prefix) {
  const random = Math.random().toString(36).slice(2, 8);
  return `${prefix}-${Date.now()}-${random}`;
}
function nowIso() {
  return (/* @__PURE__ */ new Date()).toISOString();
}

// src/storage/sessionFormat.ts
var METADATA_HEADER = "## Metadata (JSON)";
function serializeSessionToMarkdown(session) {
  const lines = [];
  lines.push(`# ${session.title}`);
  lines.push("");
  lines.push(`- Session ID: \`${session.id}\``);
  lines.push(`- Status: \`${session.status}\``);
  lines.push(`- Created: ${session.createdAt}`);
  lines.push(`- Updated: ${session.updatedAt}`);
  if (session.lastRun) {
    lines.push(`- Last Command: \`${session.lastRun.command}\``);
    lines.push(`- Last CWD: \`${session.lastRun.cwd}\``);
    lines.push(`- Last Exit Code: \`${String(session.lastRun.exitCode)}\``);
    lines.push(`- Last Duration (ms): \`${session.lastRun.durationMs}\``);
    lines.push(`- Last Cancelled: \`${String(session.lastRun.cancelled)}\``);
    lines.push(`- Last Timed Out: \`${String(session.lastRun.timedOut)}\``);
  }
  lines.push("");
  lines.push("## Transcript");
  lines.push("");
  for (const message of session.messages) {
    lines.push(`### ${message.role.toUpperCase()} (${message.createdAt})`);
    lines.push(message.content.length > 0 ? message.content : "_(empty)_");
    lines.push("");
  }
  lines.push(METADATA_HEADER);
  lines.push("```json");
  lines.push(JSON.stringify(session, null, 2));
  lines.push("```");
  lines.push("");
  return lines.join("\n");
}
function parseSessionFromMarkdown(markdown) {
  const regex = new RegExp(`${escapeRegex(METADATA_HEADER)}\\s*\\n\`\`\`json\\s*\\n([\\s\\S]*?)\\n\`\`\``);
  const match = markdown.match(regex);
  if (!match?.[1]) {
    return null;
  }
  try {
    const parsed = JSON.parse(match[1]);
    if (!parsed.id || !parsed.createdAt || !parsed.updatedAt || !Array.isArray(parsed.messages)) {
      return null;
    }
    return parsed;
  } catch {
    return null;
  }
}
function createMessage(role, content = "") {
  return {
    id: createId2(`msg-${role}`),
    role,
    content,
    createdAt: nowIso2()
  };
}
function createId2(prefix) {
  const random = Math.random().toString(36).slice(2, 8);
  return `${prefix}-${Date.now()}-${random}`;
}
function nowIso2() {
  return (/* @__PURE__ */ new Date()).toISOString();
}
function escapeRegex(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// src/storage/sessionStore.ts
var SessionStore = class {
  constructor(app, getSettings) {
    this.app = app;
    this.getSettings = getSettings;
  }
  async createSession(initialPrompt = "New chat") {
    const now = nowIso();
    const session = {
      id: createId("session"),
      title: makeTitle(initialPrompt),
      status: "idle",
      createdAt: now,
      updatedAt: now,
      messages: []
    };
    await this.saveSession(session);
    return session;
  }
  async saveSession(session) {
    session.updatedAt = nowIso();
    await this.ensureFolderExists(this.getChatFolderPath());
    if (!session.filePath) {
      const filename = `${formatTimestamp(session.createdAt)}-${slugify(session.title)}-${session.id}.md`;
      session.filePath = (0, import_obsidian2.normalizePath)(`${this.getChatFolderPath()}/${filename}`);
    }
    const content = serializeSessionToMarkdown(session);
    const existing = this.app.vault.getAbstractFileByPath(session.filePath);
    if (existing instanceof import_obsidian2.TFile) {
      await this.app.vault.modify(existing, content);
      return;
    }
    await this.app.vault.create(session.filePath, content);
  }
  async loadSessions() {
    const folderPath = this.getChatFolderPath();
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!(folder instanceof import_obsidian2.TFolder)) {
      return [];
    }
    const sessions = [];
    for (const child of folder.children) {
      if (!(child instanceof import_obsidian2.TFile) || !child.path.endsWith(".md")) {
        continue;
      }
      const content = await this.app.vault.read(child);
      const parsed = parseSessionFromMarkdown(content);
      if (!parsed) {
        continue;
      }
      parsed.filePath = child.path;
      sessions.push(parsed);
    }
    return sessions.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
  }
  async updateStatus(session, status, lastRun) {
    session.status = status;
    if (lastRun) {
      session.lastRun = lastRun;
    }
    await this.saveSession(session);
    return session;
  }
  getChatFolderPath() {
    const configured = this.getSettings().chatFolder.trim();
    return (0, import_obsidian2.normalizePath)(configured.length > 0 ? configured : "AI Chats");
  }
  async ensureFolderExists(folderPath) {
    const cleanPath = (0, import_obsidian2.normalizePath)(folderPath);
    if (this.app.vault.getAbstractFileByPath(cleanPath)) {
      return;
    }
    const segments = cleanPath.split("/").filter(Boolean);
    let current = "";
    for (const segment of segments) {
      current = current ? `${current}/${segment}` : segment;
      const existing = this.app.vault.getAbstractFileByPath(current);
      if (!existing) {
        await this.app.vault.createFolder(current);
      }
    }
  }
};
function makeTitle(prompt) {
  const clean = prompt.replace(/\s+/g, " ").trim();
  if (!clean) {
    return `Chat ${(/* @__PURE__ */ new Date()).toLocaleString()}`;
  }
  return clean.length > 48 ? `${clean.slice(0, 48)}...` : clean;
}
function slugify(input) {
  const cleaned = input.toLowerCase().replace(/[^a-z0-9\s-]/g, "").trim().replace(/\s+/g, "-").slice(0, 50);
  return cleaned || "session";
}
function formatTimestamp(isoTime) {
  return isoTime.replace(/[:.]/g, "-");
}

// src/ui/chatView.ts
var import_obsidian4 = require("obsidian");

// src/runner/agentRunner.ts
var import_node_child_process = require("node:child_process");
var AgentRunner = class {
  activeRun = null;
  async run(request, command, onStream) {
    if (this.activeRun) {
      throw new Error("Runner is already executing a request.");
    }
    const startedAt = Date.now();
    let timedOut = false;
    let spawnError = null;
    let stderr = "";
    return await new Promise((resolve) => {
      const child = (0, import_node_child_process.spawn)(command.command, command.args, {
        cwd: command.cwd,
        env: {
          ...process.env,
          ...command.env ?? {}
        },
        shell: command.shell ?? false,
        windowsHide: true
      });
      this.activeRun = {
        child,
        cancelled: false
      };
      const timeoutHandle = request.timeoutMs > 0 ? setTimeout(() => {
        timedOut = true;
        this.cancel("timeout");
      }, request.timeoutMs) : null;
      child.stdout.on("data", (chunk) => {
        onStream({
          type: "stdout",
          text: chunk.toString("utf8"),
          at: (/* @__PURE__ */ new Date()).toISOString()
        });
      });
      child.stderr.on("data", (chunk) => {
        const text = chunk.toString("utf8");
        stderr += text;
        onStream({
          type: "stderr",
          text,
          at: (/* @__PURE__ */ new Date()).toISOString()
        });
      });
      child.on("error", (err) => {
        spawnError = err;
      });
      child.on("close", (code, signal) => {
        if (timeoutHandle) {
          clearTimeout(timeoutHandle);
        }
        const activeRun = this.activeRun;
        this.activeRun = null;
        resolve({
          exitCode: code,
          signal,
          durationMs: Date.now() - startedAt,
          cancelled: activeRun?.cancelled ?? false,
          timedOut,
          stderr,
          error: spawnError ? {
            message: spawnError.message,
            code: "SPAWN_ERROR",
            raw: spawnError
          } : void 0
        });
      });
    });
  }
  cancel(reason = "user") {
    if (!this.activeRun) {
      return false;
    }
    this.activeRun.cancelled = true;
    const child = this.activeRun.child;
    try {
      child.kill("SIGTERM");
    } catch {
    }
    setTimeout(() => {
      if (!child.killed) {
        try {
          child.kill("SIGKILL");
        } catch {
        }
      }
    }, reason === "timeout" ? 500 : 900);
    return true;
  }
  isRunning() {
    return this.activeRun !== null;
  }
};

// src/ui/confirmModal.ts
var import_obsidian3 = require("obsidian");
var CommandConfirmModal = class extends import_obsidian3.Modal {
  constructor(app, preview, assessment) {
    super(app);
    this.preview = preview;
    this.assessment = assessment;
  }
  resolvePromise = null;
  async confirm() {
    return await new Promise((resolve) => {
      this.resolvePromise = resolve;
      this.open();
    });
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h3", { text: "Confirm risky command" });
    contentEl.createEl("p", {
      text: "This command was flagged as dangerous. Review before continuing."
    });
    const code = contentEl.createEl("pre");
    code.createEl("code", { text: this.preview.command });
    contentEl.createEl("p", { text: `Working directory: ${this.preview.cwd}` });
    contentEl.createEl("p", { text: `Timeout: ${this.preview.timeoutMs} ms` });
    contentEl.createEl("h4", { text: "Matched risk rules" });
    const list = contentEl.createEl("ul");
    for (const reason of this.assessment.reasons) {
      list.createEl("li", { text: reason });
    }
    new import_obsidian3.Setting(contentEl).addButton(
      (button) => button.setButtonText("Cancel").setWarning().onClick(() => this.finish(false))
    ).addButton(
      (button) => button.setButtonText("Run anyway").setCta().onClick(() => this.finish(true))
    );
  }
  onClose() {
    if (this.resolvePromise) {
      this.resolvePromise(false);
      this.resolvePromise = null;
    }
    this.contentEl.empty();
  }
  finish(value) {
    if (!this.resolvePromise) {
      return;
    }
    const resolve = this.resolvePromise;
    this.resolvePromise = null;
    resolve(value);
    this.close();
  }
};

// src/ui/chatView.ts
var CHAT_VIEW_TYPE = "local-agent-chat-view";
var ChatView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  runner = new AgentRunner();
  sessionSelectEl = null;
  statusEl = null;
  messagesEl = null;
  inputEl = null;
  sendButtonEl = null;
  stopButtonEl = null;
  sessions = [];
  currentSession = null;
  saveTimer = null;
  getViewType() {
    return CHAT_VIEW_TYPE;
  }
  getDisplayText() {
    return "Local Agent Chat";
  }
  getIcon() {
    return "messages-square";
  }
  async onOpen() {
    this.buildLayout();
    await this.refreshSessions();
    if (!this.currentSession) {
      await this.createSession("New chat");
    } else {
      this.renderMessages();
    }
  }
  async onClose() {
    if (this.saveTimer) {
      window.clearTimeout(this.saveTimer);
      this.saveTimer = null;
    }
    this.runner.cancel();
  }
  buildLayout() {
    this.contentEl.empty();
    this.contentEl.addClass("local-agent-chat");
    const header = this.contentEl.createDiv({ cls: "local-agent-chat__header" });
    this.sessionSelectEl = header.createEl("select", { cls: "local-agent-chat__session-select" });
    this.sessionSelectEl.addEventListener("change", () => {
      void this.handleSessionChange();
    });
    const refreshButton = header.createEl("button", {
      text: "Refresh",
      cls: "mod-muted"
    });
    refreshButton.addEventListener("click", () => {
      void this.refreshSessions();
    });
    const newButton = header.createEl("button", {
      text: "New Chat",
      cls: "mod-cta"
    });
    newButton.addEventListener("click", () => {
      void this.createSession("New chat");
    });
    this.statusEl = this.contentEl.createDiv({ cls: "local-agent-chat__status" });
    this.messagesEl = this.contentEl.createDiv({ cls: "local-agent-chat__messages" });
    const composer = this.contentEl.createDiv({ cls: "local-agent-chat__composer" });
    this.inputEl = composer.createEl("textarea", {
      cls: "local-agent-chat__input",
      attr: {
        placeholder: "Type a prompt. Optional: !cmd <command> on first line to run raw command."
      }
    });
    this.inputEl.addEventListener("keydown", (event) => {
      if (event.key === "Enter" && !event.shiftKey) {
        event.preventDefault();
        void this.handleSend();
      }
    });
    const buttonRow = composer.createDiv({ cls: "local-agent-chat__buttons" });
    this.sendButtonEl = buttonRow.createEl("button", {
      text: "Send",
      cls: "mod-cta"
    });
    this.sendButtonEl.addEventListener("click", () => {
      void this.handleSend();
    });
    this.stopButtonEl = buttonRow.createEl("button", {
      text: "Stop",
      cls: "mod-warning"
    });
    this.stopButtonEl.addEventListener("click", () => {
      const cancelled = this.runner.cancel("user");
      if (cancelled) {
        this.setStatus("Cancelling current run...");
      }
    });
    this.syncUiState();
  }
  async refreshSessions() {
    this.sessions = await this.plugin.sessionStore.loadSessions();
    if (this.sessions.length === 0) {
      this.currentSession = null;
    } else if (!this.currentSession) {
      this.currentSession = this.sessions[0];
    } else {
      const matched = this.sessions.find((session) => session.id === this.currentSession?.id) ?? null;
      this.currentSession = matched ?? this.sessions[0];
    }
    this.renderSessionOptions();
    this.renderMessages();
  }
  async createSession(seedPrompt) {
    const session = await this.plugin.sessionStore.createSession(seedPrompt);
    this.sessions.unshift(session);
    this.currentSession = session;
    this.renderSessionOptions();
    this.renderMessages();
    this.setStatus("Created new session.");
  }
  async handleSessionChange() {
    if (!this.sessionSelectEl) {
      return;
    }
    const id = this.sessionSelectEl.value;
    const matched = this.sessions.find((session) => session.id === id);
    if (!matched) {
      return;
    }
    this.currentSession = matched;
    this.renderMessages();
    this.setStatus(`Loaded session: ${matched.title}`);
  }
  renderSessionOptions() {
    if (!this.sessionSelectEl) {
      return;
    }
    this.sessionSelectEl.empty();
    if (this.sessions.length === 0) {
      const option = this.sessionSelectEl.createEl("option", {
        text: "No session"
      });
      option.value = "";
      return;
    }
    for (const session of this.sessions) {
      const option = this.sessionSelectEl.createEl("option", {
        text: `${session.title} (${shortTime(session.updatedAt)})`
      });
      option.value = session.id;
      if (this.currentSession && session.id === this.currentSession.id) {
        option.selected = true;
      }
    }
  }
  renderMessages() {
    if (!this.messagesEl) {
      return;
    }
    this.messagesEl.empty();
    if (!this.currentSession) {
      this.messagesEl.createDiv({ text: "No active session." });
      this.syncUiState();
      return;
    }
    for (const message of this.currentSession.messages) {
      const wrapper = this.messagesEl.createDiv({
        cls: `local-agent-chat__message local-agent-chat__message--${message.role}`
      });
      wrapper.createDiv({
        cls: "local-agent-chat__message-meta",
        text: `${message.role.toUpperCase()} \u2022 ${shortTime(message.createdAt)}`
      });
      const body = wrapper.createEl("pre", { cls: "local-agent-chat__message-body" });
      body.setText(message.content || "(empty)");
    }
    this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
    this.syncUiState();
  }
  async handleSend() {
    const inputEl = this.inputEl;
    if (!inputEl) {
      return;
    }
    const rawText = inputEl.value.trim();
    if (!rawText) {
      return;
    }
    if (this.runner.isRunning()) {
      new import_obsidian4.Notice("Another request is already running in this view.");
      return;
    }
    if (!this.currentSession) {
      await this.createSession(rawText);
      if (!this.currentSession) {
        return;
      }
    }
    const parsedInput = parseUserInput(rawText, this.plugin.settings.allowAnyCommand);
    inputEl.value = "";
    const session = this.currentSession;
    session.messages.push(createMessage("user", rawText));
    const assistantMessage = createMessage("assistant", "");
    session.messages.push(assistantMessage);
    session.status = "running";
    await this.plugin.sessionStore.saveSession(session);
    this.renderMessages();
    this.setStatus("Running command...");
    const context = {
      cwd: this.plugin.getDefaultCwd(),
      sessionId: session.id,
      vaultPath: this.plugin.getVaultPath()
    };
    let commandSpec;
    try {
      commandSpec = this.plugin.adapter.buildCommand(parsedInput, context);
    } catch (err) {
      session.status = "failed";
      session.messages.push(createMessage("system", `Command build failed: ${String(err)}`));
      await this.plugin.sessionStore.saveSession(session);
      this.renderMessages();
      this.setStatus("Failed to build command.");
      return;
    }
    session.messages.push(
      createMessage(
        "system",
        `Command preview:
${commandSpec.displayCommand}
CWD: ${commandSpec.cwd}
Timeout: ${this.plugin.settings.executionTimeoutMs}ms`
      )
    );
    await this.plugin.sessionStore.saveSession(session);
    this.renderMessages();
    const assessment = this.plugin.safetyPolicy.assess(commandSpec, context.vaultPath);
    if (assessment.isDangerous && this.plugin.settings.dangerousConfirmEnabled) {
      const modal = new CommandConfirmModal(this.app, {
        command: commandSpec.displayCommand,
        cwd: commandSpec.cwd,
        timeoutMs: this.plugin.settings.executionTimeoutMs
      }, assessment);
      const confirmed = await modal.confirm();
      if (!confirmed) {
        session.status = "cancelled";
        assistantMessage.content = "Execution cancelled by safety confirmation.";
        await this.plugin.sessionStore.saveSession(session);
        this.renderMessages();
        this.setStatus("Cancelled by safety confirmation.");
        return;
      }
    }
    this.syncUiState();
    let stderrBuffer = "";
    const result = await this.runner.run(
      {
        sessionId: session.id,
        input: parsedInput,
        timeoutMs: this.plugin.settings.executionTimeoutMs
      },
      commandSpec,
      (event) => {
        if (event.type === "stderr") {
          stderrBuffer += event.text;
          return;
        }
        const parsed = this.plugin.adapter.parseChunk(event.text);
        if (parsed.kind === "delta") {
          assistantMessage.content += parsed.text;
        } else if (parsed.text.length > 0) {
          assistantMessage.content += `
${parsed.text}`;
        }
        this.renderMessages();
        this.scheduleSave();
      }
    );
    if (stderrBuffer.trim().length > 0) {
      session.messages.push(createMessage("system", `stderr:
${stderrBuffer.trim()}`));
    }
    const status = resolveStatus(result.exitCode, result.cancelled, result.timedOut, result.error);
    session.status = status;
    if (!assistantMessage.content.trim()) {
      assistantMessage.content = result.cancelled ? "(cancelled)" : "(no output)";
    }
    const summary = {
      command: commandSpec.displayCommand,
      cwd: commandSpec.cwd,
      exitCode: result.exitCode,
      durationMs: result.durationMs,
      cancelled: result.cancelled,
      timedOut: result.timedOut,
      stderr: result.stderr || void 0
    };
    session.lastRun = summary;
    if (result.error) {
      session.messages.push(createMessage("system", `Execution error: ${result.error.message}`));
    } else if (status === "failed") {
      session.messages.push(
        createMessage(
          "system",
          `Command exited with non-zero status ${String(result.exitCode)} after ${result.durationMs}ms.`
        )
      );
    }
    await this.plugin.sessionStore.saveSession(session);
    this.sessions = this.sessions.map((item) => item.id === session.id ? session : item);
    this.sessions.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
    this.renderSessionOptions();
    this.renderMessages();
    this.setStatus(formatStatusMessage(status, result.durationMs));
  }
  scheduleSave() {
    if (!this.currentSession) {
      return;
    }
    if (this.saveTimer) {
      window.clearTimeout(this.saveTimer);
    }
    this.saveTimer = window.setTimeout(() => {
      this.saveTimer = null;
      if (this.currentSession) {
        void this.plugin.sessionStore.saveSession(this.currentSession);
      }
    }, 350);
  }
  syncUiState() {
    const running = this.runner.isRunning();
    if (this.sendButtonEl) {
      this.sendButtonEl.disabled = running;
    }
    if (this.stopButtonEl) {
      this.stopButtonEl.disabled = !running;
    }
    if (this.sessionSelectEl) {
      this.sessionSelectEl.disabled = running;
    }
  }
  setStatus(text) {
    if (!this.statusEl) {
      return;
    }
    this.statusEl.setText(text);
    this.syncUiState();
  }
};
function parseUserInput(raw, allowAnyCommand) {
  if (!allowAnyCommand || !raw.startsWith("!cmd ")) {
    return { prompt: raw };
  }
  const lines = raw.split(/\r?\n/g);
  const firstLine = lines[0].slice("!cmd ".length).trim();
  const prompt = lines.slice(1).join("\n").trim();
  return {
    prompt: prompt || "Run the command and summarize output.",
    commandOverride: firstLine
  };
}
function shortTime(isoTime) {
  const date = new Date(isoTime);
  if (Number.isNaN(date.getTime())) {
    return isoTime;
  }
  return date.toLocaleString();
}
function resolveStatus(exitCode, cancelled, timedOut, error) {
  if (cancelled || timedOut) {
    return "cancelled";
  }
  if (error) {
    return "failed";
  }
  if (exitCode === 0 || exitCode === null) {
    return "completed";
  }
  return "failed";
}
function formatStatusMessage(status, durationMs) {
  if (status === "completed") {
    return `Completed in ${durationMs} ms`;
  }
  if (status === "cancelled") {
    return `Cancelled after ${durationMs} ms`;
  }
  if (status === "failed") {
    return `Failed after ${durationMs} ms`;
  }
  return status;
}

// src/main.ts
var LocalAgentChatPlugin = class extends import_obsidian5.Plugin {
  settings = { ...DEFAULT_SETTINGS };
  sessionStore;
  adapter;
  safetyPolicy;
  async onload() {
    await this.loadSettings();
    this.sessionStore = new SessionStore(this.app, () => this.settings);
    this.adapter = new CodexCLIAdapter(() => this.settings);
    this.safetyPolicy = new SafetyPolicy();
    this.registerView(CHAT_VIEW_TYPE, (leaf) => new ChatView(leaf, this));
    this.addSettingTab(new LocalAgentSettingTab(this.app, this));
    this.addCommand({
      id: "open-local-agent-chat",
      name: "Open Local Agent Chat",
      callback: () => {
        void this.activateChatView();
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-open", () => {
      })
    );
  }
  async onunload() {
    await this.app.workspace.getLeavesOfType(CHAT_VIEW_TYPE).reduce(async (prev, leaf) => {
      await prev;
      await leaf.setViewState({ type: "empty" });
    }, Promise.resolve());
  }
  async activateChatView() {
    const existingLeaves = this.app.workspace.getLeavesOfType(CHAT_VIEW_TYPE);
    let leaf = existingLeaves[0] ?? null;
    if (!leaf) {
      leaf = this.app.workspace.getRightLeaf(false);
      if (!leaf) {
        return;
      }
      await leaf.setViewState({ type: CHAT_VIEW_TYPE, active: true });
    }
    this.app.workspace.revealLeaf(leaf);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  getVaultPath() {
    const adapter = this.app.vault.adapter;
    if (typeof adapter.getBasePath === "function") {
      return adapter.getBasePath();
    }
    return this.app.vault.configDir;
  }
  getDefaultCwd() {
    return this.settings.defaultCwd.trim() || this.getVaultPath();
  }
};
